print('NFC West       W   L  T')
print('-----------------------')
print('Seattle        13  3  0')
print('San Francisco  12  4  0')
print('Arizona        10  6  0')
print('St. Louis      7   9  0')
print()
print('NFC North      W   L  T')
print('-----------------------')
print('Green Bay      8   7  1')
print('Chicago        8   8  0')
print('Detroit        7   9  0')
print('Minnesota      5  10  1')