print('SHIP NAME      CLASS          DEPLOYMENT IN SERVICE')
print('N2 Bomber      Heavy Fighter  Limited    21        ')
print('J-Type 327     Light Combat   Unlimited  1         ')
print('NX Cruiser     Medium Fighter Limited    18        ')
print('N1 Starfighter Medium Fighter Unlimited  25        ')
print('Royal Cruiser  Light Combat   Limited    4         ')